- name: "[Ubuntu] Set NOPASSWD in sudo group"
  lineinfile:
    dest: "{{ vars_role_sudo_config_path }}" 
    regexp: '^#?%sudo'
    line: "%sudo	ALL=(ALL:ALL) NOPASSWD:ALL"
    state: present
  when:
    - input_role_os_distribution == "Ubuntu"

- name: "[CentOS] Set NOPASSWD in sudo group"
  lineinfile:
    dest: "{{ vars_role_sudo_config_path }}" 
    regexp: '^#?%wheel'
    line: "%wheel	ALL=(ALL:ALL) NOPASSWD:ALL"
    state: present
  when:
    - input_role_os_distribution == "CentOS"