- name: "Create Technical group: {{ vars_jenkins_master_system_user.username }}"
  group:
    name: "{{ vars_jenkins_master_system_user.username }}"
    state: present
    gid: "{{ vars_jenkins_master_system_user.gid }}"

- name: "Create Technical user: {{ vars_jenkins_master_system_user.username }}"
  user:
    name:     "{{ vars_jenkins_master_system_user.username }}"
    comment:  "{{ vars_jenkins_master_system_user.comment }}"
    shell:    "{{ vars_jenkins_master_system_user.shell }}"
    groups:   "{{ vars_jenkins_master_system_user.groups |default(omit) }}"
    uid:      "{{ vars_jenkins_master_system_user.uid |default(omit) }}"
    group:    "{{ vars_jenkins_master_system_user.gid |default(omit) }}"
    home:     "{{ input_role_paths.jenkins_home_path }}"
  register: test

- name: Create {{ input_role_paths.jenkins_home_path }}/.ssh user directory
  become_user: "{{ vars_jenkins_master_system_user.username }}"
  file:
    state: directory
    path: "{{ input_role_paths.jenkins_home_path }}/.ssh"
    owner: "{{ vars_jenkins_master_system_user.username }}"
    mode: 0700

- name: Create private ssh key
  become_user: "{{ vars_jenkins_master_system_user.username }}"
  copy:
    content: "{{ input_role_jenkins_ssh_key.private_ssh_key }}"
    dest: "{{ input_role_paths.jenkins_home_path }}/.ssh/id_rsa"
    owner: "{{ vars_jenkins_master_system_user.username }}"
    mode: 0600

- name: Create public ssh key
  become_user: "{{ vars_jenkins_master_system_user.username }}"
  copy:
    content: "{{ input_role_jenkins_ssh_key.public_ssh_key }}"
    dest: "{{ input_role_paths.jenkins_home_path }}/.ssh/id_rsa.pub"
    owner: "{{ vars_jenkins_master_system_user.username }}"
    mode: 0600

- name: SELinux setup context
  shell: "chcon -R unconfined_u:object_r:user_home_t:s0 {{ input_role_paths.jenkins_home_path }}"
  when: input_role_os_distribution == "CentOS"

- name: SELinux setup context
  shell: "chcon -R unconfined_u:object_r:ssh_home_t:s0 {{ input_role_paths.jenkins_home_path }}/.ssh"
  when: input_role_os_distribution == "CentOS"