- name: "[Ubuntu] Add openjdk stable repository from PPA and install its signing key on Debian target"
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    codename: trusty

- name: "[Ubuntu] Update"
  apt:
    update_cache: yes
    upgrade: dist

- name: "[Ubuntu] Install tools"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - acl
    - openjdk-8-jdk
    - openssl
    - git
