- name: "[Ubuntu] Update"
  apt:
    update_cache: yes
    upgrade: dist
  when: input_role_os_distribution == "Ubuntu"

- name: "[Ubuntu] Install tools"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - acl
    - openjdk-8-jdk
    - openssl
  when: input_role_os_distribution == "Ubuntu"

- name: "[Ubuntu] Add openjdk stable repository from PPA and install its signing key on Debian target"
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    codename: trusty
  when: input_role_os_distribution == "Ubuntu"

- name: "[CentOS] Update all packages"
  yum:
    name: '*'
    state: latest
  when: input_role_os_distribution == "CentOS"

- name: "[CentOS] Install tools"
  yum:
    name:
    - ca-certificates
    - curl
    - acl
    - java-11-openjdk.x86_64
    - openssl
  when: input_role_os_distribution == "CentOS"