---
- name: "Create workes {{ vars_role_jenkins_slave_user_template.name }}{{ item }} if ont exist"
  user:
    name: "{{ vars_role_jenkins_slave_user_template.name }}{{ item }}"
    comment: "{{ vars_role_jenkins_slave_user_template.comment }}{{ item }}"
    group: "{{ vars_role_jenkins_group.name }}"
    groups: "{{ input_role_jenkins_add_workers_to_groups }}"
    uid: "3502{{ item }}"
    home: "{{ input_role_paths.jenkins_slaves_home_path }}/{{ vars_role_jenkins_slave_user_template.name }}{{ item }}"
    shell: /bin/bash

- name: "Set authorized {{ vars_role_jenkins_slave_user_template.name }}{{ item }}"
  become_user: "{{ vars_role_jenkins_slave_user_template.name }}{{ item }}"
  authorized_key:
    user: "{{ vars_role_jenkins_slave_user_template.name }}{{ item }}"
    state: present
    key: "{{ input_role_jenkins_ssh_key.public_ssh_key }}"