---
- name: "[Ubuntu] Add openjdk stable repository from PPA and install its signing key on Debian target"
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    codename: trusty
  when: input_role_os_distribution == "Ubuntu"

- name: Install openjdk
  apt:
    name: openjdk-8-jdk
    state: present
  when: input_role_os_distribution == "Ubuntu"