---
- name: Install openjdk
  include: install_openjdk.yml

- name: Create worker gruop
  include: crate_worker_group.yml

- name: "Create Agent user: {{ vars_jenkins_master_system_user.username }}" 
  include: create_workers.yml
  with_sequence: start=1 count={{ input_role_jenkins_slave_numer_of_workers }}