---
- name: Configure sudo
  include: configure_sudo.yml

- name: Configure ssh
  include: configure_ssh.yml

- name: Set hostname
  include: set_hostname.yml

- name: install tools
  include: install_tools.yml

- name: install tools
  include: install_docker.yml