---
input_role_os_distribution: Ubuntu

input_role_ssh_configuration:
  PasswordAuthentication: "no"
  Port: 22
  PermitRootLogin: "no"

# Optional see vars role
inventory_group_jenkins_technical_account:
  username: jenkins 
  comment: "Jenkins - technical user account"
  shell: /bin/bash
  groups: docker, sudo
  uid: 30001

# Directories infrastructure
inventory_group_jenkins_volumes:
  volume_path: /volumes
  jenkins_home_path: /volumes/jenkins
  jenkins_slaves_home_path: /volumes/jenkins/slaves
  ssl_cert_dir: /volumes/ssl