---
vars_role_jenkins_group:
  name: "{{ input_role_jenkins_slaves_group.name }}"
  gid:  "{{ input_role_jenkins_slaves_group.gid }}"

vars_role_jenkins_slave_user_template:
  name: "jenkins_"
  comment: "Jenkins Slave - Worker_"
  uid: "3502"
  shell: /bin/bash