---
- name: "Create configuration {{input_role_paths.jenkins_home_path }}/jenkins.yaml"
  template:
    src:   jenkins/jenkins.yaml.j2
    dest:  "{{ input_role_paths.jenkins_home_path }}/jenkins.yaml"
    mode:  0644
  register: jenkins_caac_status

- name: Set configuration is changed
  set_fact:
    return_Ansible_Jenkins_ReloadConfiguration_configuration_changed: "{{ jenkins_caac_status.changed }}"