
- name: Check docker image is exist
  changed_when: false
  shell: docker image ls wolfsea89/jenkins_master |grep 1.0.0.1
  register: docker_image_status

- name: Docker pull
  shell: docker pull wolfsea89/jenkins_master:1.0.0.1
  when: docker_image_status.stdout_lines == ""

- name: Stop and clean jenkins
  shell: docker rm -f jenkins_master
  ignore_errors: yes

- name: Start jenkins
  shell: |
    docker run -d \
    --name jenkins_master \
    --user "{{ vars_jenkins_master_system_user.uid }}:{{ vars_jenkins_master_system_user.gid }}" \
    --publish 8080:8080 \
    --publish 50000:50000 \
    --volume "{{ input_role_paths.jenkins_home_path }}:/var/jenkins_home:z" \
    --volume "{{ input_role_paths.ssl_cert_dir }}:/etc/ssl" \
    --restart always \
     wolfsea89/jenkins_master:1.0.0.1