---
- name: Configure Jenkins Slave linux
  hosts: jenkins_slave_linux
  become: yes
  tasks:
  - include_role:
      name: Jenkins.PrepareOs
    vars:
      input_role_os_distribution: "{{ inventory_host_os_distribution }}"