---
- name: Configure Jenkins Slave linux
  hosts: jenkins_slave_linux
  become: yes
  tasks:
  - include_role:
      name: Jenkins.PrepareOs
    vars:
      input_role_os_distribution: "{{ inventory_host_os_distribution }}"
      # Technical account
      input_role_technical_account: "{{ inventory_group_jenkins_technical_account }}"
      input_role_jenkins_ssh_key: "{{ inventory_group_jenkins_ssh_key }}"
      # Directories structure
      input_role_paths: "{{ inventory_group_jenkins_paths }}"
      # CA-certificate
      input_role_jenkins_ssl_cert: "{{ inventory_group_jenkins_ssl_certificate }}"
